CREATE TABLE IF NOT EXISTS items (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    sku VARCHAR(255) NOT NULL,
    qty VARCHAR(255) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    order_id UUID,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES "orders"(id) ON DELETE CASCADE
);
