spring:
  application:
    name: order-query
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_query_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Nadi.3344}

  jpa:
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_query_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Nadi.3344}
    baseline-on-migrate: true
    schemas:
      - public
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.flywaydb: DEBUG
